#pragma once

#include "apex/core/parse_error.hpp"

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <variant>
#include <vector>
#include <utility>

namespace apex::formats {

// INI files are text, but they are still untrusted input.  These limits are
// deliberately separate from binary ParseLimits because a single physical
// line and a logical (continued) value have different failure modes.
struct IniParseLimits {
    std::size_t maxInputBytes = 64U * 1024U * 1024U;
    std::size_t maxLineBytes = 1U * 1024U * 1024U;
    std::size_t maxLines = 1'000'000;
    std::size_t maxSections = 100'000;
    std::size_t maxEntries = 1'000'000;
    std::size_t maxEntriesPerSection = 100'000;
    std::size_t maxComments = 1'000'000;
    std::size_t maxSectionNameBytes = 1U * 1024U * 1024U;
    std::size_t maxKeyBytes = 1U * 1024U * 1024U;
    std::size_t maxValueBytes = 4U * 1024U * 1024U;
    std::size_t maxContinuationLines = 1024;
};

struct IniWarning {
    std::string source;
    std::size_t line = 0;
    std::string message;
};

struct IniComment {
    // The delimiter is retained (for example "; generated by CSP") so a
    // caller can reproduce or inspect the source without losing information.
    std::string text;
    std::size_t line = 0;
};

struct IniValue {
    using Typed = std::variant<std::string, double, std::vector<double>>;

    std::string raw;
    Typed typed;

    [[nodiscard]] bool is_string() const noexcept {
        return std::holds_alternative<std::string>(typed);
    }
    [[nodiscard]] bool is_number() const noexcept {
        return std::holds_alternative<double>(typed);
    }
    [[nodiscard]] bool is_numbers() const noexcept {
        return std::holds_alternative<std::vector<double>>(typed);
    }
    [[nodiscard]] const std::string* string_value() const noexcept {
        return std::get_if<std::string>(&typed);
    }
    [[nodiscard]] const double* number_value() const noexcept {
        return std::get_if<double>(&typed);
    }
    [[nodiscard]] const std::vector<double>* numbers_value() const noexcept {
        return std::get_if<std::vector<double>>(&typed);
    }
};

struct IniEntry {
    std::string key;
    std::string value;
    IniValue typed;
    // The first physical line containing this entry. continuation_lines lists
    // each physical line that ended with a continuation marker, including the
    // first line when applicable, in source order.
    std::size_t line = 0;
    std::vector<std::size_t> continuation_lines;
};

struct IniSection {
    std::string name;
    std::size_t line = 0;
    std::string source;
    std::vector<IniEntry> entries;

    [[nodiscard]] const IniEntry* last_entry(std::string_view key) const noexcept;
    [[nodiscard]] std::vector<const IniEntry*> all_entries(std::string_view key) const;
    [[nodiscard]] std::string last_value(std::string_view key,
                                         std::string_view fallback = {}) const;
    [[nodiscard]] std::vector<std::string> all_values(std::string_view key) const;
    [[nodiscard]] const IniValue* last_typed_value(std::string_view key) const noexcept;
    [[nodiscard]] std::vector<const IniValue*> all_typed_values(std::string_view key) const;

    // Camel-case aliases ease migration from the JavaScript primitive while
    // the snake-case names remain the native API style.
    [[nodiscard]] const IniEntry* lastEntry(std::string_view key) const noexcept {
        return last_entry(key);
    }
    [[nodiscard]] std::string lastValue(std::string_view key,
                                        std::string_view fallback = {}) const {
        return last_value(key, fallback);
    }
};

struct IniRecord {
    enum class Kind { section, entry, comment };

    Kind kind = Kind::comment;
    std::size_t line = 0;
    std::size_t section_index = 0;
    std::size_t entry_index = 0;
    std::size_t comment_index = 0;
};

struct IniDocument {
    std::string source;
    std::vector<IniSection> sections;
    std::vector<IniComment> comments;
    // Records retain the source order across sections, entries, and comments.
    // Blank lines carry no record because they have no semantic payload.
    std::vector<IniRecord> records;
    std::vector<IniWarning> warnings;
    std::size_t bytes_read = 0;
    std::size_t line_count = 0;

    [[nodiscard]] const IniSection* section(std::string_view name) const noexcept;
    [[nodiscard]] std::vector<const IniSection*> sections_named(std::string_view name) const;
};

// CSP list/value primitives.  They intentionally do not evaluate selectors,
// templates, or effects; those layers consume this lossless document.
[[nodiscard]] std::vector<std::string> split_csp_list(std::string_view value);
[[nodiscard]] IniValue parse_csp_value(std::string_view value);

[[nodiscard]] inline const IniEntry* last_entry(const IniSection& section,
                                                std::string_view key) noexcept {
    return section.last_entry(key);
}
[[nodiscard]] inline std::vector<const IniEntry*> all_entries(const IniSection& section,
                                                              std::string_view key) {
    return section.all_entries(key);
}
[[nodiscard]] inline std::string last_value(const IniSection& section, std::string_view key,
                                            std::string_view fallback = {}) {
    return section.last_value(key, fallback);
}
[[nodiscard]] inline std::vector<std::string> all_values(const IniSection& section,
                                                         std::string_view key) {
    return section.all_values(key);
}
[[nodiscard]] inline const IniValue* last_typed_value(const IniSection& section,
                                                      std::string_view key) noexcept {
    return section.last_typed_value(key);
}
[[nodiscard]] inline std::vector<const IniValue*> all_typed_values(const IniSection& section,
                                                                   std::string_view key) {
    return section.all_typed_values(key);
}

[[nodiscard]] IniDocument parse_ini(std::string_view text,
                                    std::string source = "config.ini",
                                    IniParseLimits limits = {});
[[nodiscard]] IniDocument parse_ini(std::span<const std::uint8_t> bytes,
                                    std::string source = "config.ini",
                                    IniParseLimits limits = {});
[[nodiscard]] IniDocument parse_ini(std::span<const std::byte> bytes,
                                    std::string source = "config.ini",
                                    IniParseLimits limits = {});

// CSP naming is kept as an explicit alias so call sites communicate intent.
[[nodiscard]] IniDocument parse_csp_ini(std::string_view text,
                                        std::string source = "ext_config.ini",
                                        IniParseLimits limits = {});
[[nodiscard]] IniDocument parse_csp_ini(std::span<const std::uint8_t> bytes,
                                        std::string source = "ext_config.ini",
                                        IniParseLimits limits = {});
[[nodiscard]] IniDocument parse_csp_ini(std::span<const std::byte> bytes,
                                        std::string source = "ext_config.ini",
                                        IniParseLimits limits = {});

inline IniDocument parseIni(std::string_view text, std::string source = "config.ini",
                            IniParseLimits limits = {}) {
    return parse_ini(text, std::move(source), limits);
}
inline IniDocument parseCspIni(std::string_view text, std::string source = "ext_config.ini",
                               IniParseLimits limits = {}) {
    return parse_csp_ini(text, std::move(source), limits);
}
inline std::vector<std::string> splitCspList(std::string_view value) {
    return split_csp_list(value);
}
inline IniValue parseCspValue(std::string_view value) { return parse_csp_value(value); }

}  // namespace apex::formats
