import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { findAcdEntry, parseAcd } from "../src/acd.js";
import { applyDriverBasePose, auditDriverHiddenObjects, auditDriverRig, findDriverModelAsset, parseDriver3dIni } from "../src/driver-workspace.js";
import { parseKnh } from "../src/knh.js";
import { parseKsAnimation } from "../src/ksanim.js";
import { parseKn5 } from "../src/kn5.js";
import { assettoPath } from "./fixture-paths.js";

test("parses driver model, animation timing, and hidden objects",()=>{const config=parseDriver3dIni(`[MODEL]\nNAME=driver\nPOSITION=.1,.2,.3\n[STEER_ANIMATION]\nNAME=steer.ksanim\nLOCK=360\n[SHIFT_ANIMATION]\nBLEND_TIME=100\nPOSITIVE_TIME=300\nSTATIC_TIME=10\nNEGATIVE_TIME=300\nPRELOAD_RPM=7000\nINVERT_SHIFTING_HANDS=1\n[HIDE_OBJECT_0]\nNAME=DRIVER:HELMET\n`);assert.deepEqual(config.model,{name:"driver",position:[.1,.2,.3]});assert.equal(config.steer.lock,360);assert.equal(config.shift.invertHands,true);assert.deepEqual(config.hideObjects,["DRIVER:HELMET"]);assert.equal(config.warnings.length,0);});

test("auto-selects only one exact configured driver basename",()=>{const one={relativePath:"content/driver/Driver_No_HANS.kn5",file:{name:"Driver_No_HANS.kn5"}},duplicate={relativePath:"backup/driver_no_HANS.kn5",file:{name:"driver_no_HANS.kn5"}};assert.equal(findDriverModelAsset([one],"driver_no_HANS").entry,one);assert.equal(findDriverModelAsset([one,duplicate],"driver_no_HANS").status,"ambiguous");assert.equal(findDriverModelAsset([one],"driver").status,"missing");assert.equal(findDriverModelAsset([one],"").status,"unconfigured");});

test("audits an installed packed driver config, base pose, and animations",async(t)=>{const directory=assettoPath("content/cars/ks_nissan_370z");let packed,pose,steer,shift;try{[packed,pose,steer,shift]=await Promise.all([readFile(`${directory}/data.acd`),readFile(`${directory}/driver_base_pos.knh`),readFile(`${directory}/animations/steer.ksanim`),readFile(`${directory}/animations/shift.ksanim`)]);}catch{t.skip("Assetto Corsa driver fixtures are not installed");return;}const archive=parseAcd(packed,"ks_nissan_370z"),config=parseDriver3dIni(new TextDecoder().decode(findAcdEntry(archive,"driver3d.ini").data)),audit=auditDriverRig(config,{pose:parseKnh(pose),steerAnimation:parseKsAnimation(steer,"steer.ksanim"),shiftAnimation:parseKsAnimation(shift,"shift.ksanim")});assert.equal(config.model.name,"driver_no_HANS");assert.equal(audit.poseNodes,71);assert.ok(audit.steer.matched>40);assert.ok(audit.shift.matched>10);assert.equal(audit.errors,0);});

test("applies an installed car-specific KNH pose to a shared driver model",async(t)=>{const car=assettoPath("content/cars/ks_nissan_370z/driver_base_pos.knh"),driver=assettoPath("content/driver/driver_no_HANS.kn5");let pose,model;try{[pose,model]=await Promise.all([readFile(car),readFile(driver)]);}catch{t.skip("Assetto Corsa shared driver fixtures are not installed");return;}const result=applyDriverBasePose(parseKn5(model),parseKnh(pose));assert.equal(result.applied,59);assert.equal(result.unmatchedPose.length,11);});

test("resolves cockpit-hidden driver subtrees without hiding unrelated meshes",()=>{const mesh=(name)=>({kind:"mesh",name,children:[]}),model={root:{kind:"node",name:"ROOT",children:[{kind:"node",name:"DRIVER:HELMET",children:[mesh("HELMET_A"),mesh("HELMET_B")]},{kind:"node",name:"DRIVER:BODY",children:[mesh("BODY")]}]}};const audit=auditDriverHiddenObjects(model,["driver:helmet","MISSING","DRIVER:HELMET"]);assert.equal(audit.requested,2);assert.equal(audit.matched,1);assert.equal(audit.meshCount,2);assert.deepEqual(audit.unmatched,["MISSING"]);});

test("matches the installed driver's configured cockpit-hidden objects",async(t)=>{const car=assettoPath("content/cars/ks_nissan_370z/data.acd"),driver=assettoPath("content/driver/driver_no_HANS.kn5");let packed,model;try{[packed,model]=await Promise.all([readFile(car),readFile(driver)]);}catch{t.skip("Assetto Corsa shared driver fixtures are not installed");return;}const archive=parseAcd(packed,"ks_nissan_370z"),config=parseDriver3dIni(new TextDecoder().decode(findAcdEntry(archive,"driver3d.ini").data)),audit=auditDriverHiddenObjects(parseKn5(model),config.hideObjects);assert.equal(audit.requested,2);assert.equal(audit.matched,2);assert.equal(audit.meshCount,6);assert.deepEqual(audit.unmatched,[]);});
