import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { parseCspIni } from "../src/csp-config.js";
import { CSP_NOISE_DDS_SHA256, sampleCspNoise } from "../src/csp-noise.js";
import { buildGrassInstances, evaluateGrassFx, grassAtlasRect, grassBacklitResponse, grassColorThreshold, grassDeformationOcclusion, grassDeformationResponse, grassDistanceFade, grassFakeShadow, grassGenerationSchedule, grassLightingFactors, grassLinearColor, grassLocalLightResponse, grassMaterialResponse, grassNormalAoTargetNormal, grassPixelRandomFactors, grassRepeatCount, grassShapeAcceptance, grassSingleness, grassSurfaceMapCenter, grassTangentSpaceNormal, grassTrimPhase, grassWetFactors, parseGrassFx, GRASS_FX_DEFAULT_GRID, GRASS_FX_DEFAULT_TEXTURE, GRASS_FX_DEFORMATION_RADIUS, GRASS_FX_DEFORMATION_RESOLUTION, GRASS_FX_INSTANCE_STRIDE } from "../src/grass-fx.js";
import { assettoPath } from "./fixture-paths.js";

const identity=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
function packedTangent(x,y,z){const buffer=new ArrayBuffer(4),view=new DataView(buffer);view.setUint32(0,(Math.round((x+1)*.5*255)&255)|((Math.round((y+1)*.5*255)&255)<<8)|((Math.round((z+1)*.5*255)&255)<<16),true);return view.getFloat32(0,true);}
function fixture(){const vertices=new Float32Array([
  0,0,0, 0,1,0, 0,0, 1,0,0,
  1,0,0, 0,1,0, 1,0, 1,0,0,
  0,0,1, 0,1,0, 1,1, 1,0,0
]),node={kind:"mesh",name:"TERRAIN",materialId:0,vertexStride:11,vertices,indices:new Uint16Array([0,2,1]),children:[]},material={name:"Grass",shader:"ksMultilayer",resources:[]};return {model:{root:{kind:"node",name:"ROOT",children:[node]},materials:[material]},item:{node,material,world:identity,sampleDiffuse:()=>[10,70,5,255]}};}

test("parses GrassFX substrate, mask, shape, atlas, and area controls",()=>{const config=parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass, Sand\nHEIGHT_MULT=0.5\nEDGE_MULT=1.2\nCOLOR_FACTOR=1.1\nMASK_MAIN_THRESHOLD=1\nMASK_RED_THRESHOLD=0.04\nSHAPE_SIZE=0.8\nTEXTURE_BRIGHTNESS=0.85\n[GRASS_FX_AREA_...]\nCENTER=10,20\nSIZE=100\nCORNER_RADIUS=20\nMODE=ADD\nHEIGHT_MULT=0.3,0.8`);const grass=parseGrassFx(config);assert.equal(grass.grassMaterials,"Grass, Sand");assert.equal(grass.heightMult,.5);assert.equal(grass.maskMainThreshold,1);assert.equal(grass.texture,GRASS_FX_DEFAULT_TEXTURE);assert.deepEqual(grass.textureGrid,GRASS_FX_DEFAULT_GRID);assert.equal(grass.textureBrightness,.85);assert.deepEqual(grass.areas[0].size,[100,100]);assert.deepEqual(grass.areas[0].heightMult,[.3,.8]);});

test("uses legacy GrassFX texture slots and deterministic first-row atlas cells",()=>{const grass=parseGrassFx(parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nTEXTURE=grass_fx/highlands.dds\nTEXTURE_SLOTS=8,3`));assert.deepEqual(grass.textureGrid,[8,3]);const first=grassAtlasRect(grass,42),second=grassAtlasRect(grass,42);assert.deepEqual(first,second);assert.equal(first[1],0);assert.equal(first[2],1/8);assert.equal(first[3],1/3);assert.ok(first[0]>=0&&first[0]<=7/8);});

test("parses weighted GrassFX groups, rectangular pieces, width-height scaling, and adjustment maps",()=>{const grass=parseGrassFx(parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nTEXTURE_GRID=4,3\nSHAPE_SIZE=0.5,2.25\n[GRASS_FX_TEXTURE_GROUP_0]\nPIECE_0=2,1,2,2\nPIECE_0_CHANCE=0.25\nPIECE_0_SIZE_MULT=0.8,1.4\nPIECE_0_WIND=0.5\nPIECE_1=1,1\nPIECE_1_SIZE_MULT=1,2\n[GRASS_FX_CONFIGURATION_A]\nTEXTURE_BASE_CHANCE=5\nTEXTURE_GROUP_0_CHANCE=0.5\n[GRASS_FX_ADJUSTMENT_GRASS]\nMATERIALS=Grass\nMAP=A,0.5`));assert.deepEqual(grass.baseConfiguration.shapeSize,[.5,2.25]);assert.equal(grass.configurations.A.textureBaseChance,5);assert.deepEqual(grass.configurations.A.textureGroupChances,[.5,0,0,0]);assert.deepEqual(grass.textureGroups[0].pieces[0].rect,[.25,1/3,.5,2/3]);assert.deepEqual(grass.textureGroups[0].pieces[0].sizeMult,[.8,1.4]);assert.equal(grass.textureGroups[0].pieces[0].chance,.25);assert.equal(grass.textureGroups[0].pieces[0].wind,.5);assert.equal(grass.textureGroups[0].pieces[1].wind,.5);assert.deepEqual(grass.adjustments[0].map,[.5,0,0,0]);assert.equal(grass.adjustments[0].supported,true);});

test("expands GrassFX extra-area mixins and native rotated texture pieces",()=>{const grass=parseGrassFx(parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\n[GRASS_FX_ADJUSTMENT_AREA]\nMATERIALS=Grass\nMAP=C,0.5\n@ = GrassFX_ExtraArea, Map = B, Center = "-350, 0, -300", Range = 140, Fade = 20, Aspect = 3.5, Angle = 40, Opacity = 0.75\n[GRASS_FX_ADJUSTMENT_PIECE]\nCENTER=10,2,20\nSIZE=30,40\nANGLE=25\nMAP=A\nTEXTURE=piece.dds\nTEXTURE_OFFSET=.1,.2\nTEXTURE_SCALE=2,3`)),area=grass.adjustments[0],piece=grass.adjustments[1];assert.deepEqual(area.extras,[{color:[0,1,0,0],center:[-350,-300],range:[120,140],aspectRatio:3.5,angle:40,opacity:.75}]);assert.equal(piece.supported,true);assert.deepEqual(piece.piece,{center:[10,2,20],size:[30,40],angle:25,texture:"piece.dds",textureOffset:[.1,.2],textureScale:[2,3]});});

test("routes material adjustments and emits configured non-base atlas pieces deterministically",()=>{const {model,item}=fixture(),config=parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nTEXTURE_GRID=4,2\n[GRASS_FX_TEXTURE_GROUP_0]\nPIECE_0=2,1,2,1\nPIECE_0_SIZE_MULT=2\n[GRASS_FX_CONFIGURATION_A]\nMASK_MAIN_THRESHOLD=1\nSHAPE_WIDTH=1.5\nTEXTURE_BASE_CHANCE=0\nTEXTURE_GROUP_0_CHANCE=1\n[GRASS_FX_ADJUSTMENT_GRASS]\nMATERIALS=Grass\nMAP=A`),evaluation=evaluateGrassFx(model,config),a=buildGrassInstances([item],evaluation,{maxInstances:40}),b=buildGrassInstances([item],evaluation,{maxInstances:40}),targetNormal=grassNormalAoTargetNormal([0,1,0]),targetLean=targetNormal[0]/Math.hypot(targetNormal[0],targetNormal[1]+2,targetNormal[2]);assert.deepEqual(evaluation.mappedMeshes,[1,0,0,0]);assert.equal(a.configurationCounts.A,a.instanceCount);assert.equal(a.configurationCounts.BASE,0);assert.equal(a.baseInstances,0);assert.deepEqual(a.groupInstances,[a.instanceCount,0,0,0]);for(let offset=0;offset<a.instances.length;offset+=GRASS_FX_INSTANCE_STRIDE){assert.deepEqual(Array.from(a.instances.slice(offset+8,offset+12)),[.25,.5,.5,.5]);const repeat=a.instances[offset+12]/a.instances[offset+3]/.5;assert.ok(Math.abs(repeat-Math.round(repeat))<1e-5&&repeat>=1-1e-5&&repeat<=4+1e-5);assert.equal(a.instances[offset+13],.5);assert.equal(a.instances[offset+14],0);assert.ok(Math.abs(a.instances[offset+15]-targetLean)<1e-6);assert.ok(Math.abs(a.instances[offset+16]-targetLean)<1e-6);assert.ok(Number.isInteger(a.instances[offset+18]));}assert.equal(a.windMin,.5);assert.equal(a.windMax,.5);assert.deepEqual(a.instances,b.instances);});

test("interpolates adjustment configurations sequentially like the CSP constant buffer",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nSHAPE_WIDTH=1\n[GRASS_FX_CONFIGURATION_A]\nMASK_MAIN_THRESHOLD=1\nSHAPE_WIDTH=3\n[GRASS_FX_ADJUSTMENT_GRASS]\nMATERIALS=Grass\nMAP=A,0.5`)),result=buildGrassInstances([item],evaluation,{maxInstances:40});assert.equal(result.configurationCounts.MIX,result.instanceCount);assert.equal(result.configurationCounts.BASE,0);assert.equal(result.configurationCounts.A,0);for(let offset=0;offset<result.instances.length;offset+=GRASS_FX_INSTANCE_STRIDE)assert.ok(Math.abs(result.instances[offset+12]/result.instances[offset+3]-2)<1e-5);});

test("parses native adjustment masks and routes sampled multilayer channels",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nMASK_BLUR=3\nCOLOR_SAMPLE_MIP_LEVEL=9\n[GRASS_FX_CONFIGURATION_A]\nMASK_MAIN_THRESHOLD=1\nSHAPE_WIDTH=2\n[GRASS_FX_ADJUSTMENT_GRASS]\nMATERIALS=Grass\nUSE_MULTILAYER_MASK=1\nMASK_R=A,3\nMASK_G=-10\nMASK_B=B,3\nMASK_A=C`));const adjustment=evaluation.adjustments[0];assert.equal(evaluation.maskBlur,3);assert.equal(evaluation.colorSampleMipLevel,2);assert.deepEqual(adjustment.maskChannels[0],[3,0,0,0]);assert.deepEqual(adjustment.maskChannels[1],[-10,-10,-10,-10]);assert.equal(adjustment.supported,true);item.sampleGrassAdjustment=()=>[1,0,0,0];const result=buildGrassInstances([item],evaluation,{maxInstances:40});assert.equal(result.configurationCounts.A,result.instanceCount);for(let offset=0;offset<result.instances.length;offset+=GRASS_FX_INSTANCE_STRIDE)assert.ok(Math.abs(result.instances[offset+12]/result.instances[offset+3]-2)<1e-5);});

test("rasterizes and filters the native RGBA8 GrassFX adjustment target",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nMASK_BLUR=3\nSHAPE_WIDTH=1\n[GRASS_FX_CONFIGURATION_A]\nMASK_MAIN_THRESHOLD=1\nSHAPE_WIDTH=3\n[GRASS_FX_ADJUSTMENT_GRASS]\nMATERIALS=Grass\nMAP=A`)),result=buildGrassInstances([item],evaluation,{maxInstances:40,adjustmentTarget:true});assert.equal(result.adjustmentMapMode,"sparse-0.5m-rgba8-mips+native-blur-high");assert.equal(result.adjustmentTargetTileSize,32);assert.ok(result.adjustmentTargetTiles>0);assert.equal(result.adjustmentTargetPixels,result.adjustmentTargetTiles*result.adjustmentTargetTileSize**2);assert.ok(result.adjustmentRawFragments>0);assert.ok(result.adjustmentFinalTexels>0);assert.equal(result.adjustmentBlurSamples,result.adjustmentFinalTexels*21);assert.equal(result.configurationCounts.MIX,result.instanceCount);assert.equal(result.configurationCounts.A,0);});

test("renders adjustment rules in order and applies piece and ellipse overwrites",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nMASK_BLUR=0\n[GRASS_FX_CONFIGURATION_A]\nMASK_MAIN_THRESHOLD=1\n[GRASS_FX_CONFIGURATION_B]\nMASK_MAIN_THRESHOLD=1\n[GRASS_FX_CONFIGURATION_C]\nMASK_MAIN_THRESHOLD=1\n[GRASS_FX_ADJUSTMENT_FIRST]\nMATERIALS=Grass\nMAP=A\n[GRASS_FX_ADJUSTMENT_EXTRAS]\nMATERIALS=Grass\nMAP=C\n@=GrassFX_ExtraArea, Map=B, Center="0.5,0,0.5", Range=20, Fade=10\n[GRASS_FX_ADJUSTMENT_PIECE]\nCENTER=.5,0,.5\nSIZE=1,1\nMAP=B\nTEXTURE=piece.dds`));let textureSamples=0;evaluation.adjustments[2].sampleTexture=()=>{textureSamples++;return[255,255,255,255];};const result=buildGrassInstances([item],evaluation,{maxInstances:40,adjustmentTarget:true});assert.equal(result.adjustmentRules,3);assert.equal(result.adjustmentPieces,1);assert.equal(result.adjustmentExtraAreas,1);assert.ok(textureSamples>0);assert.equal(result.configurationCounts.A,0);assert.equal(result.configurationCounts.C,0);assert.equal(result.configurationCounts.B+result.configurationCounts.MIX,result.instanceCount);});

test("decodes native trim weekday values and derives the cycle phase",()=>{const grass=parseGrassFx(parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nTRIM_PERIOD=THURSDAY\nTRIM_PERIOD_OFFSET=0\nSHAPE_SIZE=0.5,1`));assert.equal(grass.baseConfiguration.trim.code,-4);assert.equal(grassTrimPhase(grass.baseConfiguration,{date:new Date("2026-08-06T00:00:00Z")}),0);assert.ok(Math.abs(grassTrimPhase(grass.baseConfiguration,{date:new Date("2026-08-12T00:00:00Z")})-6/7)<1e-9);const numeric=parseGrassFx(parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nTRIM_PERIOD=30`));assert.equal(numeric.baseConfiguration.trim.code,30);assert.ok(Math.abs(grassTrimPhase(numeric.baseConfiguration,{date:new Date("2026-01-16T00:00:00Z")})-.5)<1e-9);});

test("interpolates GrassFX shape endpoints over the trim cycle instead of randomizing them",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=10\nMASK_MAIN_THRESHOLD=1\nTRIM_PERIOD=THURSDAY\nSHAPE_SIZE=0.5,1\nSHAPE_WIDTH=1,2\nSHAPE_CUT=1,0.5\nSHAPE_TIDY=1,0.5`)),cut=buildGrassInstances([item],evaluation,{maxInstances:20,date:new Date("2026-08-06T00:00:00Z")}),grown=buildGrassInstances([item],evaluation,{maxInstances:20,date:new Date("2026-08-12T00:00:00Z")});assert.equal(cut.instanceCount,grown.instanceCount);assert.equal(cut.trimStates.BASE.phase,0);assert.ok(Math.abs(grown.trimStates.BASE.phase-6/7)<1e-9);assert.equal(cut.trimStates.BASE.shapeSize,.5);assert.equal(cut.trimStates.BASE.shapeWidth,1);assert.ok(grown.trimStates.BASE.shapeSize>.9);assert.ok(grown.trimStates.BASE.shapeWidth>1.8);assert.equal(cut.trimStates.BASE.shapeCut,1);const meanHeight=(value)=>Array.from({length:value.instanceCount},(_,index)=>value.instances[index*GRASS_FX_INSTANCE_STRIDE+3]).reduce((sum,height)=>sum+height,0)/value.instanceCount;assert.ok(meanHeight(grown)>meanHeight(cut));});

test("matches the native GrassFX shape-size rejection thresholds for preview passes",()=>{assert.equal(grassShapeAcceptance(.5,0),1);assert.equal(grassShapeAcceptance(1,0),1);assert.equal(grassShapeAcceptance(2,0),.5);assert.equal(grassShapeAcceptance(2,1),1);assert.equal(grassShapeAcceptance(4,2),.5);});
test("matches native GrassFX atlas-repeat width selection",()=>{assert.equal(grassRepeatCount({edgeAlpha:1,width:.1,passId:0,effectiveSize:.4,randomValue:0}),2);assert.equal(grassRepeatCount({edgeAlpha:1,width:.1,passId:1,effectiveSize:1,randomValue:1}),2);assert.equal(grassRepeatCount({edgeAlpha:1,width:.01,passId:1,effectiveSize:1,randomValue:1}),4);assert.equal(grassRepeatCount({edgeAlpha:.5,width:.1,passId:1,effectiveSize:1,randomValue:0}),1);assert.equal(grassRepeatCount({edgeAlpha:1,width:.1,passId:4,effectiveSize:1,randomValue:0}),2);assert.equal(grassRepeatCount({edgeAlpha:1,width:.01,passId:4,effectiveSize:2,randomValue:1}),4);assert.equal(grassRepeatCount({edgeAlpha:1,width:.01,allowRepeat:false}),1);});

test("matches the native medium camera-ring dispatch schedule and two-meter snapping",()=>{const passes=grassGenerationSchedule({position:[10,3,20],direction:[0,0,-2]});assert.deepEqual(passes.map(({spacing,divisor,step,side,width})=>({spacing,divisor,step,side,width})),[{spacing:1,divisor:16,step:.25,side:128,width:32},{spacing:.5,divisor:8,step:.125,side:512,width:64},{spacing:2,divisor:4,step:.5,side:256,width:128},{spacing:2,divisor:2,step:.5,side:512,width:256},{spacing:4,divisor:1,step:1,side:512,width:512}]);assert.deepEqual(passes.map((pass)=>pass.snappedCenter),[[10,16],[10,0],[10,-32],[10,-96],[10,-226]]);assert.deepEqual(passes.map((pass)=>pass.start),[[-6,0],[-22,-32],[-54,-96],[-118,-224],[-246,-482]]);assert.equal(passes.reduce((sum,pass)=>sum+pass.side**2,0),868352);});
test("holds the snapped GrassFX target until native 16 m refresh hysteresis",()=>{const camera={position:[10,3,20],direction:[0,0,-1]},initial=grassSurfaceMapCenter(camera);assert.deepEqual(initial,[10,-226]);assert.deepEqual(grassSurfaceMapCenter({...camera,position:[10,3,34]},initial),initial);assert.deepEqual(grassSurfaceMapCenter({...camera,position:[10,3,36]},initial),[10,-210]);assert.deepEqual(grassSurfaceMapCenter({...camera,position:[10,3,20],direction:[1,0,0]},initial),[256,20]);});

test("samples CSP's embedded common noise with native mip-0 linear wrapping",()=>{const center=sampleCspNoise(.5/32,.5/32),next=sampleCspNoise(1.5/32,.5/32),midpoint=sampleCspNoise(1/32,.5/32);assert.deepEqual(center.map((value)=>Math.round(value*255)),[237,109,229,194]);assert.deepEqual(next.map((value)=>Math.round(value*255)),[152,122,98,158]);assert.deepEqual(midpoint.map((value)=>Math.round(value*255*2)/2),[194.5,115.5,163.5,176]);assert.deepEqual(sampleCspNoise(.5/32+3,.5/32-2),center);assert.equal(CSP_NOISE_DDS_SHA256,"0de3092cc1207f8d0ae52d9b6e510b39d0831733a8a80a813b1bf433149adc72");});
test("matches custom_l GrassFX substrate gamma, singleness, and pixel random inputs",()=>{const color=grassLinearColor([10,70,5,255]);assert.deepEqual(color,[10,70,5].map((value)=>Math.pow(value/255*4.444444444444445,2.2)));assert.equal(grassSingleness(1,.35),0);assert.equal(grassSingleness(.5,.35),1);assert.ok(Math.abs(grassSingleness(1,.175)-.25)<1e-12);const factors=grassPixelRandomFactors([17,2,-31],[.25,.75]);assert.deepEqual(factors,grassPixelRandomFactors([17,2,-31],[.25,.75]));assert.ok(factors.every((value)=>value>=0&&value<=1));});
test("keeps custom_l GrassFX coverage separate from direct fade and ambient root AO",()=>{assert.deepEqual(grassLightingFactors({bladeY:0,fade:.4,texDimming:0,viewY:1}),{direct:.2,ambientAo:1,dimming:1});const tip=grassLightingFactors({bladeY:1,fade:.4,texDimming:1,viewY:.2});assert.equal(tip.direct,.4);assert.ok(Math.abs(tip.ambientAo-.1)<1e-12);assert.equal(tip.dimming,.5);});

test("matches custom_l wet-grass albedo, specular, and snow factors",()=>{assert.deepEqual(grassWetFactors(0),{wet:0,snowMix:0,colorMult:1,specularDirectionMult:1});const wet=grassWetFactors(1);assert.equal(wet.wet,1);assert.equal(wet.snowMix,0);assert.ok(Math.abs(wet.colorMult-Math.pow(.65,2.2))<1e-12);assert.equal(wet.specularDirectionMult,1.5);const occluded=grassWetFactors(.5,.4);assert.equal(occluded.wet,.2);assert.equal(occluded.specularDirectionMult,1.2);const snow=grassWetFactors(-.5,.4,.5);assert.deepEqual(snow,{wet:0,snowMix:.125,colorMult:1,specularDirectionMult:1});assert.equal(grassWetFactors(-2,1,1).snowMix,1);});
test("matches custom_l GrassFX fake-shadow modulation",()=>{assert.equal(grassFakeShadow(1,.8,1),1);assert.equal(grassFakeShadow(.2,.75,1),.25);assert.ok(Math.abs(grassFakeShadow(.45,.5,1)-.75)<1e-12);assert.equal(grassFakeShadow(.2,1,0),1);});
test("matches custom_l zero-default directional backlighting",()=>{const aligned=grassBacklitResponse({bladeY:1,fade:1,shadow:1,diffuse:1,distance:0,toCamera:[0,0,-1],lightDirection:[0,0,1],bent:[0,0,1],color:[1,.5,.25]});assert.equal(aligned.amount,1);assert.equal(aligned.pixelMultiplier,1);assert.ok(Math.abs(aligned.color[0]-1.41725)<1e-12);assert.ok(Math.abs(aligned.color[1]-.41725)<1e-12);assert.equal(aligned.color[2],0);assert.equal(grassBacklitResponse({bladeY:0,toCamera:[0,0,-1],lightDirection:[0,0,1],bent:[0,0,1]}).amount,0);assert.equal(grassBacklitResponse({bladeY:1,distance:72,toCamera:[0,0,-1],lightDirection:[0,0,1],bent:[0,0,1]}).amount,0);assert.equal(grassBacklitResponse({bladeY:1,toCamera:[0,0,1],lightDirection:[0,0,1],bent:[1,0,0]}).amount,0);});
test("matches the custom_l concentrated local-light and fixed gloss response",()=>{const light={position:[0,1,0],range:10,color:[2,1,.5],rangeGradientOffset:0,diffuseConcentration:1,specularMult:0},diffuse=grassLocalLightResponse(light,{normal:[0,1,0],toCamera:[0,-1,0],fade:1});assert.ok(Math.abs(diffuse.diffuse-1)<1e-12);assert.equal(diffuse.specular,0);assert.deepEqual(diffuse.color,[1.62,.81,.405]);const glossy=grassLocalLightResponse({...light,specularMult:1},{normal:[0,1,0],toCamera:[0,-1,0],fade:1});assert.equal(glossy.specular,2);assert.deepEqual(glossy.color,[4.86,2.43,1.215]);assert.equal(grassLocalLightResponse({...light,direction:[0,1,0],spot:90,spotSharpness:1},{normal:[0,1,0]}).power,0);assert.equal(grassLocalLightResponse(light,{position:[0,10,0]}).power,0);});
test("applies the optional CSP RGB spot edge and hollow secondary GrassFX cone",()=>{const light={position:[0,6,0],range:20,color:[1,1,1],rangeGradientOffset:0,diffuseConcentration:1,specularMult:0,direction:[0,-1,0],spot:30,spotSharpness:.8,hasSpotEdge:true,spotUp:[1,0,0],spotEdge:[.5,1,1],spotEdgeSharpness:1,hasSecondSpot:true,secondSpot:120,secondSpotSharpness:.8,secondSpotRange:20,secondSpotSkip:.3,secondSpotIntensity:.5},response=grassLocalLightResponse(light,{normal:[0,1,0],toCamera:[0,-1,0]});assert.ok(Math.abs(response.color[0]-.49)<1e-12);assert.ok(Math.abs(response.color[1]-.735)<1e-12);assert.ok(Math.abs(response.color[2]-.735)<1e-12);assert.ok(Math.abs(response.power-1.96)<1e-12);});
test("decodes the RGBA8 GrassFX material target into diffuse and substrate specular response",()=>{const facing=grassMaterialResponse([.2,.4,.5,8/255],{normal:[0,1,0],position:[0,0,0],cameraPosition:[0,1,0],lightDirection:[0,1,0]});assert.ok(Math.abs(facing.diffuse-Math.pow(.5,2.2))<1e-12);assert.equal(facing.specular,.5);const away=grassMaterialResponse([.2,.4,.5,8/255],{normal:[0,1,0],position:[0,0,0],cameraPosition:[0,1,0],lightDirection:[0,-1,0]});assert.equal(away.specular,0);assert.deepEqual(grassMaterialResponse(null),{diffuse:1,specular:0});});

test("matches the native GrassFX deformation response and static-editor zero field",()=>{assert.equal(GRASS_FX_DEFORMATION_RESOLUTION,1024);assert.equal(GRASS_FX_DEFORMATION_RADIUS,100);assert.deepEqual(grassDeformationResponse(0,.2),{value:0,cut:false,deformation:0,squash:0,exponent:1,heightMult:1,widthMult:1,colorMult:1,fadeMult:1,lift:[0,0]});const cut=grassDeformationResponse(1,.2);assert.equal(cut.cut,true);assert.equal(cut.deformation,0);const bent=grassDeformationResponse(.8,.2);assert.ok(bent.deformation>.5&&bent.deformation<.53);assert.ok(bent.squash>.7);assert.ok(bent.exponent<.5);assert.ok(bent.heightMult<.5);assert.ok(bent.widthMult>1);assert.ok(bent.fadeMult<.75);assert.equal(grassDeformationOcclusion([[0,0],[0,0],[0,0],[0,0]]),0);assert.ok(Math.abs(grassDeformationOcclusion([[0,1],[0,1],[0,1],[0,1]])-1)<1e-12);assert.ok(Math.abs(grassDeformationOcclusion([[0,1],[0,1],[0,1],[0,1]],{enabled:false})-.8)<1e-12);});
test("round-trips surface normals through CSP's RGBA8 normal/AO target",()=>{assert.deepEqual(grassNormalAoTargetNormal([0,1,0]),grassNormalAoTargetNormal([0,10,0]));const value=grassNormalAoTargetNormal([.6,.8,0]);assert.ok(Math.abs(Math.hypot(...value)-1)<1e-12);assert.ok(value[0]>.59&&value[0]<.61);assert.ok(value[1]>.79&&value[1]<.81);assert.ok(value[2]>0);});

test("matches the native camera-ring distance fade and LOD sink factors",()=>{assert.deepEqual(grassDistanceFade([0,3,0],3,[0,0],100),{distance:0,fade:1,lodFix:1});const midpoint=grassDistanceFade([50,3,0],3,[0,0],100);assert.ok(Math.abs(midpoint.fade-.4)<1e-12);assert.ok(Math.abs(midpoint.lodFix-.8)<1e-12);assert.equal(grassDistanceFade([62.5,3,0],3,[0,0],100).fade,0);});

test("samples the native camera rings evenly within an explicit CPU candidate budget",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nMASK_MAIN_THRESHOLD=1`)),result=buildGrassInstances([item],evaluation,{maxInstances:100,maxGenerationCandidates:100,surfaceTarget:true,camera:{position:[.5,2,2],direction:[0,-.5,-1],fovDegrees:60,aspect:1}});assert.equal(result.nativeCandidateCount,868352);assert.equal(result.generationCandidateBudget,100);assert.equal(result.candidateCount,100);assert.ok(Math.abs(result.generationSamplingRate-100/868352)<1e-12);assert.deepEqual(result.generationPasses.map((pass)=>pass.candidates),[1,31,7,30,31]);assert.deepEqual(result.generationPasses.map((pass)=>pass.nativeCandidates),[16384,262144,65536,262144,262144]);assert.equal(result.surfaceTargetMode,"sparse-camera-local-0.25m-depth-lequal+linear-clamp");assert.equal(result.surfaceTargetResolution,2048);assert.equal(result.surfaceTargetRefreshDistance,16);assert.equal(result.surfaceTargetCenterChanged,true);});

test("falls back to bounded full-source authoring when the camera window misses all grass",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=10\nMASK_MAIN_THRESHOLD=1`)),result=buildGrassInstances([item],evaluation,{maxInstances:20,maxGenerationCandidates:100,surfaceTarget:true,camera:{position:[10000,2,10000],direction:[1,0,0],fovDegrees:60,aspect:1}});assert.equal(result.generationFallbackReason,"camera-window-outside-source-bounds");assert.equal(result.generationMode,"source-triangle-stratified");assert.equal(result.nativeCandidateCount,0);assert.equal(result.generationPasses.length,0);assert.ok(result.instanceCount>0);});

test("matches source meshes and builds deterministic bounded blade instances",()=>{const {model,item}=fixture(),config=parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=10\nMASK_MAIN_THRESHOLD=1\nMASK_RED_THRESHOLD=0.04`),evaluation=evaluateGrassFx(model,config),a=buildGrassInstances([item],evaluation,{maxInstances:20}),b=buildGrassInstances([item],evaluation,{maxInstances:20});assert.equal(evaluation.sourceMeshes,1);assert.equal(evaluation.sourceTriangles,1);assert.ok(a.instanceCount>0&&a.instanceCount<=20);assert.equal(a.instanceStride,GRASS_FX_INSTANCE_STRIDE);assert.equal(a.instances.length,a.instanceCount*GRASS_FX_INSTANCE_STRIDE);assert.deepEqual(a.instances,b.instances);assert.equal(a.rejectedByMask,0);});

test("uses interpolated world surface normals for substrate sampling and blade lean",()=>{const {model,item}=fixture();for(let offset=0;offset<item.node.vertices.length;offset+=item.node.vertexStride)item.node.vertices.set([.6,.8,0],offset+3);const evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nTEXTURE_GRID=1,1\nTEXTURE_BASE_CHANCE=0\nTEXTURE_GROUP_0_CHANCE=1\n[GRASS_FX_TEXTURE_GROUP_0]\nPIECE_0=1,0`)),sampled=[];item.sampleGrassSurface=(u,v,position,mip,normal)=>{sampled.push(normal);return[10,70,5,255];};const result=buildGrassInstances([item],evaluation,{maxInstances:20}),targetNormal=sampled[0],expected=targetNormal[0]/Math.hypot(targetNormal[0],targetNormal[1]+2,targetNormal[2]),expectedZ=targetNormal[2]/Math.hypot(targetNormal[0],targetNormal[1]+2,targetNormal[2]);assert.equal(sampled.length,result.instanceCount);assert.ok(result.instanceCount>0);for(const normal of sampled){assert.ok(normal[0]>.59&&normal[0]<.61);assert.ok(normal[1]>.79&&normal[1]<.81);assert.ok(normal[2]>0&&normal[2]<.01);}for(let offset=0;offset<result.instances.length;offset+=GRASS_FX_INSTANCE_STRIDE){assert.ok(Math.abs(result.instances[offset+15]-expected)<1e-6);assert.ok(Math.abs(result.instances[offset+16]-expectedZ)<1e-6);assert.ok(Math.abs(result.instances[offset+19]-targetNormal[0])<1e-6);assert.ok(Math.abs(result.instances[offset+20]-targetNormal[2])<1e-6);}});

test("decodes packed KN5 tangents and applies CSP's tangent-space normal channel order",()=>{const {model,item}=fixture();for(let offset=0;offset<item.node.vertices.length;offset+=item.node.vertexStride)item.node.vertices[offset+8]=packedTangent(1,0,0);const evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1\nTEXTURE_GRID=1,1\nTEXTURE_BASE_CHANCE=0\nTEXTURE_GROUP_0_CHANCE=1\n[GRASS_FX_TEXTURE_GROUP_0]\nPIECE_0=1,0`)),frames=[],surfaceNormals=[];item.sampleGrassNormal=(u,v,position,mip,frame)=>{frames.push(frame);return grassTangentSpaceNormal([1,.5,.5,1],frame);};item.sampleGrassSurface=(u,v,position,mip,normal)=>{surfaceNormals.push(normal);return[10,70,5,255];};const result=buildGrassInstances([item],evaluation,{maxInstances:20});assert.ok(result.instanceCount>0);assert.equal(result.normalMode,"interpolated-world-vertex+tangent-space-map+rgba8-normal-ao-target-alpha1");assert.equal(result.normalMapSamples,result.instanceCount);for(const frame of frames){assert.ok(frame.tangent[0]>.9999);assert.ok(Math.abs(frame.tangent[1])<.01);assert.ok(frame.bitangent[2]>.9999);}for(const normal of surfaceNormals){assert.ok(normal[0]>.9999);assert.ok(Math.abs(normal[1])<.01);}for(let index=0;index<result.instanceCount;index++){const normal=surfaceNormals[index],expected=normal[0]/Math.hypot(normal[0],normal[1]+2,normal[2]);assert.ok(Math.abs(result.instances[index*GRASS_FX_INSTANCE_STRIDE+15]-expected)<1e-5);}assert.deepEqual(grassTangentSpaceNormal([.5,.5,1,1]),[0,1,0]);assert.ok(grassTangentSpaceNormal([.5,1,.5,1])[2]>.9999);});

test("subtracts projected GrassFX occluders from generated blades",()=>{const {model,item}=fixture(),occluder={...item.node,name:"ROAD",materialId:1},road={name:"Road",shader:"ksPerPixel",resources:[]};model.root.children.push(occluder);model.materials.push(road);const evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nOCCLUDING_MATERIALS=Road\nDENSITY=10\nMASK_MAIN_THRESHOLD=1\nMASK_RED_THRESHOLD=0.04`)),result=buildGrassInstances([item,{node:occluder,material:road,world:identity}],evaluation,{maxInstances:20});assert.equal(evaluation.occluderMeshes,1);assert.equal(result.instanceCount,0);assert.ok(result.rejectedByOcclusion>0);});

test("reproduces CSP's continuous GrassFX color-threshold equation",()=>{const settings=parseGrassFx(parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nMASK_MAIN_THRESHOLD=0.5\nMASK_RED_THRESHOLD=0.05\nMASK_MIN_LUMINANCE=0.02\nMASK_MAX_LUMINANCE=0.35`));assert.equal(grassColorThreshold([0,25.5,0,255],settings),1);assert.equal(grassColorThreshold([25.5,25.5,25.5,255],settings),0);assert.equal(grassColorThreshold([0,2.55,0,255],settings),0);assert.equal(grassColorThreshold([0,127.5,0,255],settings),0);});

test("scales accepted fin width and height by the continuous color threshold",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=10\nMASK_MAIN_THRESHOLD=0.5\nMASK_RED_THRESHOLD=0.05\nMASK_MIN_LUMINANCE=0.02\nMASK_MAX_LUMINANCE=0.35`));item.sampleGrassSurface=()=>[0,25.5,0,255];const full=buildGrassInstances([item],evaluation,{maxInstances:20});item.sampleGrassSurface=()=>[0,11.475,0,255];const edge=buildGrassInstances([item],evaluation,{maxInstances:20});assert.equal(full.instanceCount,edge.instanceCount);for(let index=0;index<full.instanceCount;index++){const offset=index*GRASS_FX_INSTANCE_STRIDE;assert.ok(Math.abs(edge.instances[offset+3]/full.instances[offset+3]-.5)<1e-5);const fullCellWidth=full.instances[offset+12]/full.instances[offset+10],edgeCellWidth=edge.instances[offset+12]/edge.instances[offset+10];assert.ok(Math.abs(edgeCellWidth/fullCellWidth-.5)<1e-5);}});

test("applies CSP's fixed mip-2 edge square and mip-3 tall-grass clamp",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=10\nMASK_MAIN_THRESHOLD=1\nSHAPE_SIZE=4`));item.sampleGrassSurface=()=>[10,70,5,255];item.sampleGrassEdgeAlpha=(u,v,position,mip)=>mip===2?.5:0;const edged=buildGrassInstances([item],evaluation,{maxInstances:20}),calls=edged.edgeAlphaSamples;delete item.sampleGrassEdgeAlpha;const full=buildGrassInstances([item],evaluation,{maxInstances:20});assert.equal(edged.instanceCount,full.instanceCount);assert.equal(calls,(edged.candidateCount-edged.rejectedByMask-edged.rejectedByOcclusion)*2);for(let index=0;index<full.instanceCount;index++){const offset=index*GRASS_FX_INSTANCE_STRIDE;assert.ok(Math.abs(edged.instances[offset+3]/full.instances[offset+3]-.125)<1e-5);assert.ok(Math.abs(edged.instances[offset+12]/full.instances[offset+12]-.125)<1e-5);}});

test("rasterizes geometric GrassFX edges into sparse fixed-step alpha mips",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1`));item.sampleGrassSurface=()=>[10,70,5,255];const materialOnly=buildGrassInstances([item],evaluation,{maxInstances:40}),target=buildGrassInstances([item],evaluation,{maxInstances:40,surfaceTarget:true});assert.equal(target.surfaceTargetMode,"sparse-global-0.25m-depth-lequal+four-texel-depth-gather");assert.equal(target.surfaceTargetTileSize,32);assert.ok(target.surfaceTargetTiles>0);assert.ok(target.rejectedByDepthDiscontinuity>0);assert.equal(target.surfaceTargetPixels,target.surfaceTargetTiles*target.surfaceTargetTileSize**2);assert.equal(target.edgeAlphaSamples,(target.candidateCount-target.rejectedByMask-target.rejectedByOcclusion-target.rejectedByDepthDiscontinuity)*2);const totalHeight=(result)=>{let sum=0;for(let offset=0;offset<result.instances.length;offset+=GRASS_FX_INSTANCE_STRIDE)sum+=result.instances[offset+3];return sum;};assert.ok(totalHeight(target)<totalHeight(materialOnly));});

test("samples and gamma-fixes candidate color and material from quantized RGBA8 surface targets",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1`));item.sampleGrassSurface=()=>[10.4,70.4,5.4,255];item.sampleGrassMaterial=()=>[.2,.4,.5,8/255];const target=buildGrassInstances([item],evaluation,{maxInstances:40,surfaceTarget:true}),expected=grassLinearColor([10,70,5,255]),expectedDiffuse=Math.pow(.5,2.2);assert.equal(target.surfaceColorMode,"rgba8-bilinear-mips");assert.ok(target.instanceCount>0);for(let offset=0;offset<target.instances.length;offset+=GRASS_FX_INSTANCE_STRIDE){assert.ok(Math.abs(target.instances[offset+5]-expected[0])<1e-6);assert.ok(Math.abs(target.instances[offset+6]-expected[1])<1e-6);assert.ok(Math.abs(target.instances[offset+7]-expected[2])<1e-6);assert.ok(target.instances[offset+21]>=0&&target.instances[offset+21]<=1);assert.ok(target.instances[offset+22]>=0&&target.instances[offset+22]<=1);assert.ok(target.instances[offset+23]>=0&&target.instances[offset+23]<=1);assert.ok(Math.abs(target.instances[offset+24]-expectedDiffuse)<1e-6);assert.ok(target.instances[offset+25]>=0&&target.instances[offset+25]<=128/255);}});

test("lets the highest LESS_EQUAL surface own shared GrassFX target pixels",()=>{const {model,item}=fixture(),upper={...item.node,name:"UPPER",children:[]},upperItem={node:upper,material:item.material,world:[1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1],sampleGrassSurface:()=>[10,70,5,0]};model.root.children.push(upper);item.sampleGrassSurface=()=>[10,70,5,255];const evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1`)),withoutTarget=buildGrassInstances([item,upperItem],evaluation,{maxInstances:40}),withTarget=buildGrassInstances([item,upperItem],evaluation,{maxInstances:40,surfaceTarget:true});assert.ok(withoutTarget.instanceCount>0);assert.equal(withTarget.instanceCount,0);assert.ok(withTarget.rejectedByOcclusion>0);assert.ok(withTarget.rejectedByMask>0);});

test("emits overlapping GrassFX candidates only from the top target-owning triangle",()=>{const {model,item}=fixture(),upper={...item.node,name:"UPPER",children:[]},upperItem={node:upper,material:item.material,world:[1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1],sampleGrassSurface:()=>[10,70,5,255]};model.root.children.push(upper);item.sampleGrassSurface=()=>[10,70,5,255];const evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=100\nMASK_MAIN_THRESHOLD=1`)),withoutTarget=buildGrassInstances([item,upperItem],evaluation,{maxInstances:40}),withTarget=buildGrassInstances([item,upperItem],evaluation,{maxInstances:40,surfaceTarget:true});assert.ok(Array.from({length:withoutTarget.instanceCount},(_,index)=>withoutTarget.instances[index*GRASS_FX_INSTANCE_STRIDE+1]).some((y)=>y<.5));assert.ok(withTarget.instanceCount>0);assert.ok(withTarget.rejectedBySurfaceOwnership>0);assert.equal(withTarget.rejectedByConfiguredOcclusion,0);for(let index=0;index<withTarget.instanceCount;index++)assert.ok(Math.abs(withTarget.instances[index*GRASS_FX_INSTANCE_STRIDE+1]-1)<1e-6);});

test("accepts GrassFX from the composed material-pass color rather than raw mask channels",()=>{const {model,item}=fixture(),evaluation=evaluateGrassFx(model,parseCspIni(`[GRASS_FX]\nGRASS_MATERIALS=Grass\nDENSITY=10\nMASK_MAIN_THRESHOLD=0.5\nMASK_RED_THRESHOLD=0.05\nMASK_MAX_LUMINANCE=0.35`));item.sampleGrassSurface=()=>[10,70,5,255];item.sampleMask=()=>[255,0,0,255];const grass=buildGrassInstances([item],evaluation,{maxInstances:20});assert.ok(grass.instanceCount>0);item.sampleGrassSurface=()=>[50,50,50,255];const blocked=buildGrassInstances([item],evaluation,{maxInstances:20});assert.equal(blocked.instanceCount,0);assert.ok(blocked.rejectedByMask>0);});

test("parses the installed Imola GrassFX fixture",async(t)=>{const path=assettoPath("extension/config/tracks/loaded/imola.ini");let text;try{text=await readFile(path,"utf8");}catch{t.skip("Installed CSP Imola config is unavailable");return;}const grass=parseGrassFx(parseCspIni(text,path));assert.equal(grass.grassMaterials,"Grass, top1, top2, Sand");assert.equal(grass.heightMult,.5);assert.equal(grass.areas.length,1);assert.equal(grass.maskMinLuminance,.0875);});
