import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { parseCameraSplineCsv, parseTrackCamerasIni, rotateCameraSpline, sampleCameraSpline } from "../src/track-cameras.js";

test("parses a normalized track camera and its optical metadata",()=>{const set=parseTrackCamerasIni(`[HEADER]\nVERSION=3\nCAMERA_COUNT=1\nSET_NAME=TV\n[CAMERA_0]\nNAME=Finish\nPOSITION=1,2,3\nFORWARD=0,0,-1\nUP=0,1,0\nMIN_FOV=10\nMAX_FOV=20\nIN_POINT=.9\nOUT_POINT=1\nNEAR_PLANE=.5\nFAR_PLANE=5000\nMIN_EXPOSURE=.3\nMAX_EXPOSURE=.6\nDOF_FACTOR=2\nDOF_RANGE=100\nDOF_FOCUS=50\nDOF_MANUAL=1\nSPLINE=follow.csv\nSPLINE_ROTATION=30\nSPLINE_ANIMATION_LENGTH=12\nFOV_GAMMA=.5\nIS_FIXED=0\n`);assert.equal(set.version,3);assert.equal(set.name,"TV");assert.equal(set.cameras.length,1);assert.deepEqual(set.cameras[0].position,[1,2,3]);assert.equal(set.cameras[0].spline,"follow.csv");assert.equal(set.cameras[0].dofManual,true);assert.deepEqual(set.warnings,[]);});

test("diagnoses gaps, count mismatch, invalid basis, interval, FOV, and clips",()=>{const set=parseTrackCamerasIni(`[HEADER]\nCAMERA_COUNT=2\n[CAMERA_0]\nPOSITION=0,0,0\nFORWARD=0,2,0\nUP=0,1,0\nMIN_FOV=20\nMAX_FOV=10\nIN_POINT=.8\nOUT_POINT=.2\nNEAR_PLANE=5\nFAR_PLANE=1\n[CAMERA_2]\n`);assert.equal(set.cameras.length,1);assert.ok(set.warnings.some((warning)=>warning.includes("CAMERA_2 is ignored")));assert.ok(set.warnings.some((warning)=>warning.includes("FOV range")));assert.ok(set.warnings.some((warning)=>warning.includes("perpendicular")));assert.ok(set.warnings.some((warning)=>warning.includes("clip planes")));});

test("parses, rotates, and samples camera spline offsets with the game endpoint rule",()=>{const spline=parseCameraSplineCsv("0, 0, 0\n1, 0, 0\n2, 0, 0\n","move.csv");assert.equal(spline.points.length,3);assert.equal(spline.length,2);const rotated=rotateCameraSpline(spline.points,90);assert.ok(Math.abs(rotated[1][0])<1e-12);assert.ok(Math.abs(rotated[1][2]+1)<1e-12);assert.deepEqual(sampleCameraSpline(rotated,0),rotated[0]);const end=sampleCameraSpline(rotated,1);assert.ok(Math.abs(end[2]+2.49700004)<.00001);});

test("accepts whitespace spline rows and diagnoses malformed coordinates",()=>{const spline=parseCameraSplineCsv("0 0 0\ninvalid\n0 1 0\n","space.csv");assert.deepEqual(spline.points,[[0,0,0],[0,1,0]]);assert.equal(spline.warnings.length,1);});

test("parses the installed Kunos Imola camera sets",async(t)=>{const directory="/mnt/D/SteamLibrary/SteamLibrary/steamapps/common/assettocorsa/content/tracks/imola/data";let tv,start;try{[tv,start]=await Promise.all([readFile(`${directory}/cameras.ini`,"utf8"),readFile(`${directory}/cameras_start.ini`,"utf8")]);}catch{t.skip("Assetto Corsa camera fixtures are not installed");return;}const tvSet=parseTrackCamerasIni(tv,"imola/data/cameras.ini"),startSet=parseTrackCamerasIni(start,"imola/data/cameras_start.ini");assert.equal(tvSet.version,3);assert.equal(tvSet.cameras.length,12);assert.equal(tvSet.declaredCount,12);assert.equal(startSet.cameras.length,6);assert.ok(startSet.cameras.every((camera)=>camera.fixed&&camera.inPoint===-1&&camera.outPoint===-1));assert.deepEqual(tvSet.warnings,[]);assert.deepEqual(startSet.warnings,[]);});
