#!/usr/bin/env node

// Usage: node native/tools/embed_hdr_tone_map_artifacts.mjs \
//   vertex.spv fragment.spv vertex.dxbc pixel.dxbc

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

function formatBytes(bytes) {
  const lines = [];
  for (let offset = 0; offset < bytes.length; offset += 12) {
    const values = [...bytes.subarray(offset, offset + 12)]
      .map((value) => `0x${value.toString(16).padStart(2, "0")}`);
    lines.push(`  ${values.join(", ")},`);
  }
  return lines.join("\n");
}

function array(name, bytes, { aligned = false, type = "unsigned char" } = {}) {
  const prefix = aligned ? "alignas(4) " : "";
  return `${prefix}inline constexpr ${type} ${name}[] = {\n${formatBytes(bytes)}\n};\n\ninline constexpr std::size_t ${name}_size = sizeof(${name});`;
}

const argumentsList = process.argv.slice(2);
if (argumentsList.length !== 4) {
  throw new Error("Pass vertex SPIR-V, fragment SPIR-V, vertex DXBC, and pixel DXBC paths.");
}

const [vertexSpirv, fragmentSpirv, vertexDxbc, pixelDxbc] =
  await Promise.all(argumentsList.map((path) => readFile(path)));
const toolDirectory = dirname(fileURLToPath(import.meta.url));
const generatedDirectory = resolve(toolDirectory, "../src/render/generated");

const spirvHeader = `#pragma once

#include <cstddef>

// Generated by native/tools/embed_hdr_tone_map_artifacts.mjs.
namespace apex::render::generated {

${array("hdr_tone_map_vertex_spirv", vertexSpirv, { aligned: true })}

${array("hdr_tone_map_fragment_spirv", fragmentSpirv, { aligned: true })}

} // namespace apex::render::generated
`;

const dxbcHeader = `#pragma once

#include <cstddef>
#include <cstdint>

// Generated from shaders/d3d12_hdr_tone_map.hlsl with Microsoft fxc 10.1.
// Embedded by native/tools/embed_hdr_tone_map_artifacts.mjs.
// The source and bytecode identities are enforced by a native drift test.
namespace apex::render::generated {

${array("d3d12_hdr_tone_map_vertex_dxbc", vertexDxbc, { type: "std::uint8_t" })}

${array("d3d12_hdr_tone_map_pixel_dxbc", pixelDxbc, { type: "std::uint8_t" })}

} // namespace apex::render::generated
`;

await Promise.all([
  writeFile(resolve(generatedDirectory, "hdr_tone_map_spirv.hpp"), spirvHeader),
  writeFile(resolve(generatedDirectory, "d3d12_hdr_tone_map_dxbc.hpp"), dxbcHeader)
]);
