#!/usr/bin/env node

// Usage: node native/tools/embed_directional_shadow_alpha_source_artifacts.mjs \
//   vertex.spv fragment.spv vertex.dxbc pixel.dxbc

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

function formatBytes(bytes) {
  const lines = [];
  for (let offset = 0; offset < bytes.length; offset += 12) {
    const values = [...bytes.subarray(offset, offset + 12)]
      .map((value) => `0x${value.toString(16).padStart(2, "0")}`);
    lines.push(`  ${values.join(", ")},`);
  }
  return lines.join("\n");
}

function array(name, bytes) {
  return `alignas(4) inline constexpr std::uint8_t ${name}[] = {\n${formatBytes(bytes)}\n};\n\ninline constexpr std::size_t ${name}_size = sizeof(${name});`;
}

const paths = process.argv.slice(2);
if (paths.length !== 4) {
  throw new Error("Pass vertex SPIR-V, fragment SPIR-V, vertex DXBC, and pixel DXBC paths.");
}

const [vertexSpirv, fragmentSpirv, vertexDxbc, pixelDxbc] =
  await Promise.all(paths.map((path) => readFile(path)));
const toolDirectory = dirname(fileURLToPath(import.meta.url));
const generatedDirectory = resolve(toolDirectory, "../src/render/generated");

const header = `#pragma once

#include <cstddef>
#include <cstdint>

// Generated by native/tools/embed_directional_shadow_alpha_source_artifacts.mjs.
namespace apex::render::generated {

${array("directional_shadow_alpha_source_vertex_spirv", vertexSpirv)}

${array("directional_shadow_alpha_source_fragment_spirv", fragmentSpirv)}

${array("directional_shadow_alpha_source_vertex_dxbc", vertexDxbc)}

${array("directional_shadow_alpha_source_pixel_dxbc", pixelDxbc)}

} // namespace apex::render::generated
`;

await writeFile(
  resolve(generatedDirectory, "directional_shadow_alpha_source_artifacts.hpp"),
  header,
);
