#include "apex/core/parse_error.hpp"
#include "apex/formats/bc7.hpp"

#include <array>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

using apex::core::ParseError;
using namespace apex::formats;

namespace {

void require(bool condition, std::string_view message) {
    if (!condition) throw std::runtime_error(std::string(message));
}

std::vector<std::uint8_t> hex(std::string_view value) {
    require(value.size() % 2u == 0u, "hex fixture has odd length");
    std::vector<std::uint8_t> result;
    result.reserve(value.size() / 2u);
    const auto digit = [](char c) -> std::uint8_t {
        if (c >= '0' && c <= '9') return static_cast<std::uint8_t>(c - '0');
        if (c >= 'a' && c <= 'f') return static_cast<std::uint8_t>(c - 'a' + 10);
        if (c >= 'A' && c <= 'F') return static_cast<std::uint8_t>(c - 'A' + 10);
        throw std::runtime_error("invalid hex fixture");
    };
    for (std::size_t index = 0; index < value.size(); index += 2u)
        result.push_back(static_cast<std::uint8_t>((digit(value[index]) << 4u) | digit(value[index + 1u])));
    return result;
}

template <typename Function>
void expectsBc7Error(Function&& function, std::string_view code) {
    try {
        function();
    } catch (const ParseError& error) {
        require(error.format() == "BC7" && error.code() == code, "unexpected BC7 error");
        return;
    }
    throw std::runtime_error("expected BC7 ParseError");
}

void decodesAllModesWithSharedScratch() {
    require(bc7PartitionTableValid(), "BC7 partition table has the authoritative 2048-byte size");
    Bc7Scratch scratch{};
    for (std::uint32_t mode = 0; mode < 8u; ++mode) {
        std::array<std::uint8_t, 16> block{};
        block[0] = static_cast<std::uint8_t>(1u << mode);
        std::array<std::uint8_t, 64> output{};
        decodeBc7Block(block, 0u, output, 0u, 16u, scratch, "mode-fixture");
        for (std::size_t pixel = 0; pixel < 16u; ++pixel) {
            require(output[pixel * 4u] == 0u && output[pixel * 4u + 1u] == 0u &&
                        output[pixel * 4u + 2u] == 0u,
                    "zero endpoint mode decode");
            const auto expectedAlpha = mode < 4u ? 255u : 0u;
            require(output[pixel * 4u + 3u] == expectedAlpha, "mode alpha decode");
        }
    }

    const std::array<std::uint8_t, 16> partitionFixture = {
        0x1fu, 0x12u, 0x34u, 0x56u, 0x78u, 0x9au, 0xbcu, 0xdeu,
        0xf0u, 0x11u, 0x22u, 0x33u, 0x44u, 0x55u, 0x66u, 0x77u};
    const std::array<std::uint8_t, 64> expected = {
        0u, 33u, 82u, 255u, 21u, 56u, 105u, 255u, 70u, 119u, 113u, 255u,
        46u, 95u, 108u, 255u, 46u, 96u, 238u, 255u, 86u, 128u, 177u, 255u,
        0u, 33u, 82u, 255u, 119u, 168u, 123u, 255u, 68u, 118u, 220u, 255u,
        68u, 118u, 220u, 255u, 21u, 56u, 105u, 255u, 62u, 103u, 152u, 255u,
        159u, 209u, 149u, 255u, 159u, 209u, 149u, 255u, 137u, 187u, 167u, 255u,
        62u, 103u, 152u, 255u};
    std::array<std::uint8_t, 64> output{};
    decodeBc7Block(partitionFixture, 0u, output, 0u, 16u, scratch, "partition-fixture");
    require(output == expected, "partition and interpolation decode");

    const std::array<std::uint8_t, 16> mode4Fixture = {
        0x10u, 0x23u, 0x45u, 0x67u, 0x89u, 0xabu, 0xcdu, 0xefu,
        0x01u, 0x23u, 0x45u, 0x67u, 0x89u, 0xabu, 0xcdu, 0xefu};
    const std::array<std::uint8_t, 64> mode4Expected = {
        40u, 132u, 132u, 163u, 40u, 132u, 132u, 186u, 58u, 123u, 82u, 128u,
        74u, 115u, 33u, 152u, 74u, 115u, 33u, 116u, 40u, 132u, 132u, 163u,
        74u, 115u, 33u, 163u, 74u, 115u, 33u, 139u, 24u, 140u, 181u, 152u,
        24u, 140u, 181u, 128u, 24u, 140u, 181u, 116u, 58u, 123u, 82u, 116u,
        40u, 132u, 132u, 139u, 24u, 140u, 181u, 105u, 40u, 132u, 132u, 152u,
        58u, 123u, 82u, 105u};
    decodeBc7Block(mode4Fixture, 0u, output, 0u, 16u, scratch, "mode4-fixture");
    require(output == mode4Expected, "rotation and dual-index decode");

    // Differential vectors generated by src/bc7-decoder.js. Keep one vector
    // for each mode so endpoint expansion, p-bits, anchors, partitions,
    // rotations, and dual-index selection remain source-evidenced.
    const std::array<std::pair<std::string_view, std::string_view>, 8> vectors = {{
        {"9f999997999997999bb71d11144cd7c9", "cbcbcbffcececeffceced0ffceced3ffc6c6c6ffc9c9c9ffccccccffcececeffc3c3c3ffc5c5c5ffc8c8c8ffcbcbcbffc0c0c0ffc2c2c2ffc3c3c3ffc7c7c7ff"},
        {"16f7aef739aff7f7aef734809a5eceee", "dfe7dfffe4eae4ffe9e9e9ffe9e9e9ffe6ece6ffecececffeeeeeeffecececffedf1edfff2f2f2fff0f0f0ffeeeeeefff3f3f3fff3f3f3fff2f2f2ffeeeeeeff"},
        {"14b5ced9669d678659e7995fb6686959", "d6d6d6ffd6ceceffcebebeffce9c9cffd6d6d6ffd6d3d3ffcececeffc6b6b3ffd6d6d6ffd6d3d3ffcececeffc6b6b3ffd6d6d6ffcececeffc6b6b3ffb5847bff"},
        {"d8dce17afc1daec7dfeb7a7ccf81d4a1", "eaeaedffeaeaedffe5e5ecffe0e0eaffefefefffefefefffefefefffeaeaedfff2f2f2fff2f2f2fff2f2f2fff1f1f1fff5f5f5fff5f5f5fff4f4f4fff4f4f4ff"},
        {"10000000000000000000000000000000", "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},
        {"a0801f6000f803fc01000080010000c0", "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007e7fff06"},
        {"c0caaeb233af63672412324397a9dcfe", "3535cd713535cd713535cd712f2fcd693535cd713939ce783939ce783e3ecf7f4e4ed1955757d2a25757d2a25d5dd3ab6767d4b86b6bd5bf7171d5c77676d6ce"},
        {"80009813803901f81f003100e0e1e119", ""},
    }};
    std::size_t vectorIndex = 0;
    for (const auto& [blockHex, expectedHex] : vectors) {
        const auto block = hex(blockHex);
        std::array<std::uint8_t, 64> actual{};
        decodeBc7Block(block, 0u, actual, 0u, 16u, scratch, "js-differential");
        std::vector<std::uint8_t> expectedPixels;
        if (vectorIndex == 7u) {
            expectedPixels.assign(52u, 0u);
            const auto tail = hex("9a9afb109a9afb189a9afb18");
            expectedPixels.insert(expectedPixels.end(), tail.begin(), tail.end());
        } else {
            expectedPixels = hex(expectedHex);
        }
        if (std::vector<std::uint8_t>(actual.begin(), actual.end()) != expectedPixels)
            throw std::runtime_error("BC7 JS differential vector mismatch at mode " + std::to_string(vectorIndex));
        ++vectorIndex;
    }
}

void rejectsBoundsAndMalformedModes() {
    Bc7Scratch scratch{};
    const std::array<std::uint8_t, 16> valid = {1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
                                                 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
    std::array<std::uint8_t, 64> output{};
    for (std::size_t length = 0; length < valid.size(); ++length) {
        const std::span<const std::uint8_t> prefix(valid.data(), length);
        expectsBc7Error([&] { decodeBc7Block(prefix, 0u, output, 0u, 16u, scratch, "prefix"); }, "TRUNCATED");
    }
    std::array<std::uint8_t, 16> noMode{};
    expectsBc7Error([&] { decodeBc7Block(noMode, 0u, output, 0u, 16u, scratch, "mode"); }, "INVALID_MODE");
    expectsBc7Error([&] { decodeBc7Block(valid, 1u, output, 0u, 16u, scratch, "offset"); }, "TRUNCATED");
    expectsBc7Error([&] { decodeBc7Block(valid, 0u, output, 0u, 15u, scratch, "pitch"); }, "OUTPUT_BOUNDS");
    expectsBc7Error([&] { decodeBc7Block(valid, 0u, output, 1u, 16u, scratch, "output"); }, "OUTPUT_BOUNDS");
    std::array<std::uint8_t, 10> tooSmall{};
    expectsBc7Error([&] { decodeBc7Block(valid, 0u, tooSmall, 0u, 16u, scratch, "underflow"); }, "OUTPUT_BOUNDS");
    std::array<std::uint8_t, 80> padded{};
    padded.fill(0xa5u);
    decodeBc7Block(valid, 0u, padded, 4u, 20u, scratch, "padded");
    require(padded[0] == 0xa5u && padded[20u] == 0xa5u,
            "padded output bounds preserved");
}

} // namespace

int main() {
    try {
        decodesAllModesWithSharedScratch();
        rejectsBoundsAndMalformedModes();
        std::cout << "bc7 tests passed\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "bc7 tests failed: " << error.what() << '\n';
        return 1;
    }
}
