export const identityMatrix=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
export function multiplyMatrices(a,b){const output=new Array(16).fill(0);for(let column=0;column<4;column++)for(let row=0;row<4;row++)for(let index=0;index<4;index++)output[column*4+row]+=a[index*4+row]*b[column*4+index];return output;}
export function transformPoint(matrix,value){const [x,y,z]=value;return [matrix[0]*x+matrix[4]*y+matrix[8]*z+matrix[12],matrix[1]*x+matrix[5]*y+matrix[9]*z+matrix[13],matrix[2]*x+matrix[6]*y+matrix[10]*z+matrix[14]];}
export function transformDirection(matrix,value){const [x,y,z]=value;return [matrix[0]*x+matrix[4]*y+matrix[8]*z,matrix[1]*x+matrix[5]*y+matrix[9]*z,matrix[2]*x+matrix[6]*y+matrix[10]*z];}

export function invertMatrix(a){const output=new Array(16),b00=a[0]*a[5]-a[1]*a[4],b01=a[0]*a[6]-a[2]*a[4],b02=a[0]*a[7]-a[3]*a[4],b03=a[1]*a[6]-a[2]*a[5],b04=a[1]*a[7]-a[3]*a[5],b05=a[2]*a[7]-a[3]*a[6],b06=a[8]*a[13]-a[9]*a[12],b07=a[8]*a[14]-a[10]*a[12],b08=a[8]*a[15]-a[11]*a[12],b09=a[9]*a[14]-a[10]*a[13],b10=a[9]*a[15]-a[11]*a[13],b11=a[10]*a[15]-a[11]*a[14],det=b00*b11-b01*b10+b02*b09+b03*b08-b04*b07+b05*b06;if(Math.abs(det)<1e-12)return null;const d=1/det;output[0]=(a[5]*b11-a[6]*b10+a[7]*b09)*d;output[1]=(-a[1]*b11+a[2]*b10-a[3]*b09)*d;output[2]=(a[13]*b05-a[14]*b04+a[15]*b03)*d;output[3]=(-a[9]*b05+a[10]*b04-a[11]*b03)*d;output[4]=(-a[4]*b11+a[6]*b08-a[7]*b07)*d;output[5]=(a[0]*b11-a[2]*b08+a[3]*b07)*d;output[6]=(-a[12]*b05+a[14]*b02-a[15]*b01)*d;output[7]=(a[8]*b05-a[10]*b02+a[11]*b01)*d;output[8]=(a[4]*b10-a[5]*b08+a[7]*b06)*d;output[9]=(-a[0]*b10+a[1]*b08-a[3]*b06)*d;output[10]=(a[12]*b04-a[13]*b02+a[15]*b00)*d;output[11]=(-a[8]*b04+a[9]*b02-a[11]*b00)*d;output[12]=(-a[4]*b09+a[5]*b07-a[6]*b06)*d;output[13]=(a[0]*b09-a[1]*b07+a[2]*b06)*d;output[14]=(-a[12]*b03+a[13]*b01-a[14]*b00)*d;output[15]=(a[8]*b03-a[9]*b01+a[10]*b00)*d;return output;}

export function sceneWorldMatrices(root,localTransforms=new Map()){const byNode=new Map(),byName=new Map();const visit=(node,parent)=>{const local=localTransforms.get(node.name)||node.transform,world=local?multiplyMatrices(parent,local):parent;byNode.set(node,world);if(!byName.has(node.name))byName.set(node.name,world);for(const child of node.children||[])visit(child,world);};visit(root,identityMatrix);return {byNode,byName};}

function normalized(value){const length=Math.hypot(...value);return length>1e-12?value.map((component)=>component/length):[0,0,0];}
export function skinMeshVertices(mesh,boneWorldByName,meshWorld=identityMatrix){if(mesh?.kind!=="skinnedMesh"||mesh.vertexStride!==19)throw new TypeError("Expected a 19-float KN5 skinned mesh");const inverseMesh=invertMatrix(meshWorld);if(!inverseMesh)throw new Error(`Skinned mesh ${mesh.name} has a non-invertible world transform`);const palettes=mesh.bones.map((bone)=>{const world=boneWorldByName.get(bone.name);return world?multiplyMatrices(world,bone.transform):null;}),output=new Float32Array(mesh.vertices);
  for(let offset=0;offset<mesh.vertices.length;offset+=19){const sourcePosition=[mesh.vertices[offset],mesh.vertices[offset+1],mesh.vertices[offset+2]],sourceNormal=[mesh.vertices[offset+3],mesh.vertices[offset+4],mesh.vertices[offset+5]],sourceTangent=[mesh.vertices[offset+8],mesh.vertices[offset+9],mesh.vertices[offset+10]],worldPosition=[0,0,0],worldNormal=[0,0,0],worldTangent=[0,0,0];let total=0;
    for(let influence=0;influence<4;influence++){const weight=mesh.vertices[offset+11+influence],index=mesh.vertices[offset+15+influence],palette=Number.isInteger(index)&&index>=0?palettes[index]:null;if(!(weight>0)||!palette)continue;const position=transformPoint(palette,sourcePosition),normal=transformDirection(palette,sourceNormal),tangent=transformDirection(palette,sourceTangent);for(let axis=0;axis<3;axis++){worldPosition[axis]+=position[axis]*weight;worldNormal[axis]+=normal[axis]*weight;worldTangent[axis]+=tangent[axis]*weight;}total+=weight;}
    if(total<=1e-8)continue;if(Math.abs(total-1)>1e-5)for(let axis=0;axis<3;axis++){worldPosition[axis]/=total;worldNormal[axis]/=total;worldTangent[axis]/=total;}const localPosition=transformPoint(inverseMesh,worldPosition),localNormal=normalized(transformDirection(inverseMesh,worldNormal)),localTangent=normalized(transformDirection(inverseMesh,worldTangent));output.set(localPosition,offset);output.set(localNormal,offset+3);output.set(localTangent,offset+8);
  }return output;
}
